// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrGYUMZQyrQlvUyqsMNvY0mL6lEC_15Dk',
    appId: '1:566238229277:web:54f9b11a73d6f1df7927f4',
    messagingSenderId: '566238229277',
    projectId: 'surapp-kg',
    authDomain: 'surapp-kg.firebaseapp.com',
    storageBucket: 'surapp-kg.firebasestorage.app',
    measurementId: 'G-GP11S93BQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6xdm59sFzO2jvQ8SScWIe55vzsx2RTB8',
    appId: '1:566238229277:android:d52409cb478a0d927927f4',
    messagingSenderId: '566238229277',
    projectId: 'surapp-kg',
    storageBucket: 'surapp-kg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrfjuHOBwyuA30hL8DGjFpyT4258vRHKA',
    appId: '1:566238229277:ios:56e84c9d4ad2e0ae7927f4',
    messagingSenderId: '566238229277',
    projectId: 'surapp-kg',
    storageBucket: 'surapp-kg.firebasestorage.app',
    iosBundleId: 'kg.surapp.app',
  );
}
